version: "3"
   
services:
    jwt:
        build: .
        restart: always
        ports:
        - "8000:8000"
        volumes:
            - ./certs:/project/certs
        depends_on:
          - postgresdb
    postgresdb:
        image: postgres
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
